### ISSUE TITLE
question

### ISSUE THREAD

**Issue by atherdon** [elaine-zheng/summer2020internships#1]
Hi @elaine-zheng i have a question - is there any restrictions for submit a company to your list?
I submit my company at Cristine awesome list and interested to provide a place for developer interns at my company
Tell me what do you think - thanks for your time

**Comment by elaine-zheng** [comment]
Nope- no restrictions really as long as it's generally tech. related. PM me the link

**Comment by atherdon** [comment]
I'm glad to know it

[Groceristar](https://angel.co/company/groceristar/jobs) | Remote | Present | Many positions available: Engineers, Q&A, Project manager, Personal Assistant, Growth Hacker

I also create an article that may help people to find internships: https://hackernoon.com/looking-for-a-tech-internship-try-this-list-of-online-resources-83ae85af44

**Comment by elaine-zheng** [comment]
I've added your startup to the list!

**Comment by atherdon** [comment]
big thank you! hope to be a good mentor. will add your repo to my
collection that i'm sharing with my teammates

>
