### ISSUE TITLE
A website for curating internships

### ISSUE THREAD

**Issue by imedadel** [elaine-zheng/summer2020internships#38]
Hello Elaine :)

I recently made this website, [Intern](https://intern.imedadel.me), for curating internships. For each position, I look for the average salary, duration, and locations before posting them to the website. I'm trying to keep it updated :)

I thought that the visitors of this repository might be interested in taking a look on the website.

Thank you

**Comment by aaditkamat** [comment]
There is another website I found, [techinternship.io](https://www.techinternship.io), developed by [Alex Wallish](https://www.github.com/awallish) which can help you to track your internship applications. It requires users to login with a user name and password. You can check the location, approximate pay (not updated in some cases) and also specify whether you have applied, are interviewing, have received an offer or been rejected. I would recommend you guys to check this website out as well.
