### ISSUE TITLE
Spotify not offering undergrad internships

### ISSUE THREAD

**Issue by jakegut** [elaine-zheng/summer2020internships#55]
[Spotify](https://www.spotifyjobs.com/students/) is not offering any internships suited for undergraduates, only to those who are pursuing a PhD, which is contrary to the repo description.

Will they soon be offering undergrad internships or does Spotify need to be removed?

**Comment by ghost** [comment]
[This](https://www.spotifyjobs.com/job/frontend-web-engineering-internship-summer-2020/) one is for undergraduates
